--- 
services: 
  web: 
    image: fen9li/simple-sinatra-app
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    ports: 
      - "80:4567"
version: "3"
